baseURL = "https://dericbourg.dev/"
languageCode = "fr"
DefaultContentLanguage = "fr"
title = "Alban Dericbourg"

enableEmoji = true
enableRobotsTXT = true
localizedDates = true

# Disable unused default taxonomies
[taxonomies]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # Needed: references use inline <small> tags in Markdown headings
      unsafe = true
