[fr]
title = "Alban Dericbourg — Développeur"
weight = 1
LanguageName = "🇫🇷 Français"
  [fr.params]
  description = "Je suis développeur"

[en]
title = "Alban Dericbourg — Software Engineer"
weight = 2
LanguageName = "🇬🇧 English"
  [en.params]
  description = "I am a software engineer"
