[[main]]
name       = "accueil"
identifier = "accueil"
weight     = 100
url        = "/"

[[main]]
name       = "références"
identifier = "references"
weight     = 200
url        = "/references/"

[[main]]
name       = "cv"
identifier = "cv"
weight     = 300
url        = "/cv/"

[[main]]
name       = "contact"
identifier = "contact"
weight     = 400
url        = "/contact/"

[[footer]]
name       = "malt"
identifier = "malt"
weight     = 1
url        = "https://www.malt.fr/profile/albandericbourg"
