author = "Alban Dericbourg"
favicon = "/favicon.svg"

[[socialLinks]]
label = "LinkedIn"
url   = "https://www.linkedin.com/in/adericbourg/"

[[socialLinks]]
label = "GitHub"
url   = "https://github.com/adericbourg"

[[socialLinks]]
label = "e-mail"
url   = "mailto:alban@dericbourg.dev"
